### ISSUE TITLE
Uncaught TypeError: boolean is not a function

### ISSUE THREAD

**Issue by RossHepburn** [motepair/motepair#11]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.181.0
**System**: Mac OS X 10.10.1
**Thrown From**: [motepair](https://github.com/motepair/motepair) package, v0.15.0
### Stack Trace

Uncaught TypeError: boolean is not a function

```
At /Users/rosshepburn/.atom/packages/motepair/lib/atom_attacher.js:75

TypeError: boolean is not a function
  at applyToShareJS (/Users/rosshepburn/.atom/packages/motepair/lib/atom_attacher.js:75:13)
  at onLocalChange (/Users/rosshepburn/.atom/packages/motepair/lib/atom_attacher.js:59:7)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.applyPatch (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:594:20)
  at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:507:12)
  at TextBuffer.module.exports.TextBuffer.setText (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:431:19)
  at TextEditor.module.exports.TextEditor.setText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:755:26)
  at /Users/rosshepburn/.atom/packages/motepair/lib/atom_attacher.js:95:18

```
### Commands

```
     -3:30.2 application:open-dev (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -3:21.9 core:backspace (atom-text-editor.editor)
     -3:19.8 command-palette:toggle (atom-text-editor.editor)
     -3:17.2 core:confirm (atom-text-editor.editor.mini)
     -3:17.2 motepair:connect (atom-text-editor.editor)
 19x -3:15.6 core:backspace (atom-text-editor.editor.mini)
     -3:05.8 core:paste (atom-text-editor.editor.mini)
 55x -3:04.7 core:backspace (atom-text-editor.editor.mini)
     -2:44.8 core:paste (atom-text-editor.editor.mini)
     -2:43.9 core:confirm (atom-text-editor.editor.mini)
```
### Config

``` json
{
  "core": {
    "themes": [
      "seti-ui",
      "monokai"
    ],
    "disabledPackages": [
      "atom-pair"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
linter-ruby, v0.1.4
monokai, v0.12.0
motepair, v0.15.0
seti-ui, v0.6.3

# Dev
No dev packages
```

**Comment by luizbafilho** [comment]
Hi @RossHepburn , 

We are going to need your help with this one, are you being able to reproduce that bug? 

Because, the stack trace this time is not helpful, we could not reproduce here only looking at that.

Could you please send us the steps?

Luiz Filho

**Comment by fleebzz** [comment]
Hi. I often have this error but I don't know exactly how to reproduce.

[Enter steps to reproduce below:]
1. Random ...

**Atom Version**: 1.0.11
**System**: Mac OS X 10.11
**Thrown From**: [motepair](https://github.com/motepair/motepair) package, v0.20.0

### Stack Trace

Uncaught TypeError: boolean is not a function

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:773

TypeError: boolean is not a function
    at applyToShareJS (/Users/bez/.atom/packages/motepair/lib/atom_attacher.js:75:13)
    at onLocalChange (/Users/bez/.atom/packages/motepair/lib/atom_attacher.js:59:7)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at TextBuffer.module.exports.TextBuffer.applyChange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:648:20)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:553:12)
    at LanguageMode.module.exports.LanguageMode.toggleLineCommentsForBufferRows (/Applications/Atom.app/Contents/Resources/app.asar/src/language-mode.js:79:22)
    at TextEditor._results.push._this.(anonymous function) [as toggleLineCommentsForBufferRows] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/delegato/lib/delegator.js:67:61)
    at Selection.module.exports.Selection.toggleLineComments (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:688:68)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1049:26
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:787:29
```

### Commands

```
     -8:01.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -8:01.7.0 motepair:connect (atom-text-editor.editor)
     -8:00.8.0 editor:select-to-first-character-of-line (atom-text-editor.editor.mini.is-focused)
     -8:00.5.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -8:00.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  3x -1:54.6.0 tab-switcher:next (atom-text-editor.editor.is-focused)
     -1:22.4.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -1:22.2.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:47.6.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
     -0:39.5.0 core:save (atom-text-editor.editor.is-focused)
     -0:37.1.0 tab-switcher:next (atom-text-editor.editor.is-focused)
     -0:31.3.0 editor:duplicate-lines (atom-text-editor.editor.is-focused)
     -0:14 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
     -0:10.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:09.0 core:close (atom-text-editor.editor.is-focused)
     -0:01.7.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
```

### Config

``` json
{
  "core": {
    "themes": [
      "unity-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "term2",
      "atom-pair"
    ],
    "excludeVcsIgnoredPaths": false
  },
  "motepair": {
    "userEmail": "florian@bezagu.com"
  }
}
```

### Installed Packages

``` coffee
# User
Termrk, v0.1.26
angularjs, v0.3.0
git-plus, v5.4.7
jshint, v1.6.1
motepair, v0.20.0
tab-switcher, v1.2.1
unity-ui, v2.1.0

# Dev
No dev packages
```
