### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by luizbafilho** [motepair/motepair#16]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.172.0
**System**: linux 3.13.0-40-generic
**Thrown From**: [motepair](https://github.com/motepair/motepair) package, v0.18.0
### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /home/luiz/projetos/motepair/lib/event_handler.coffee:148

TypeError: undefined is not a function
  at /home/luiz/.atom/packages/motepair/lib/event_handler.coffee:148:18
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at PaneContainer.module.exports.PaneContainer.willDestroyPaneItem (/usr/share/atom/resources/app/src/pane-container.js:311:27)
  at Pane.module.exports.Pane.destroyItem (/usr/share/atom/resources/app/src/pane.js:440:17)
  at EventHandler.onclose (/home/luiz/.atom/packages/motepair/lib/event_handler.coffee:28:32)
  at WebSocket.<anonymous> (/home/luiz/.atom/packages/motepair/lib/event_handler.coffee:84:9)
  at WebSocket.emit (events.js:129:20)
  at Receiver.ontext (/home/luiz/.atom/packages/motepair/node_modules/ws/lib/WebSocket.js:798:10)
  at /home/luiz/.atom/packages/motepair/node_modules/ws/lib/Receiver.js:473:18
  at /home/luiz/.atom/packages/motepair/node_modules/ws/lib/Receiver.js:357:7
  at /home/luiz/.atom/packages/motepair/node_modules/ws/lib/PerMessageDeflate.js:217:5
  at afterWrite (_stream_writable.js:334:3)
  at onwrite (_stream_writable.js:325:7)
  at WritableState.onwrite (_stream_writable.js:103:5)
  at afterTransform (_stream_transform.js:99:5)
  at TransformState.afterTransform (_stream_transform.js:74:12)
  at Zlib.callback (zlib.js:610:5)

```
### Commands

```
     -1:13.1 motepair:connect (input.hidden-input)
     -1:12.0 core:select-all (input.hidden-input)
     -1:11.4 editor:consolidate-selections (input.hidden-input)
     -1:10.8 application:open-file (atom-workspace.workspace.scrollbars-visible-always.theme-solarized-dark-syntax.theme-atom-dark-ui)
     -1:05.8 motepair:connect (atom-workspace.workspace.scrollbars-visible-always.theme-solarized-dark-syntax.theme-atom-dark-ui)
     -1:04.7 core:select-all (input.hidden-input)
     -0:45.1 core:confirm (input.hidden-input)
  3x -0:40.6 editor:newline (input.hidden-input)
     -0:27.0 core:select-all (input.hidden-input)
     -0:26.0 core:move-left (input.hidden-input)
  7x -0:25.6 core:move-down (input.hidden-input)
     -0:24.4 editor:select-to-end-of-line (input.hidden-input)
     -0:21.9 core:save (input.hidden-input)
     -0:08.3 core:confirm (input.hidden-input)
  2x -0:05.3 editor:newline (input.hidden-input)
  2x -0:00.0 core:save (input.hidden-input)
```
### Config

``` json
{
  "core": {
    "excludeVcsIgnoredPaths": false,
    "disabledPackages": [
      "firepad",
      "linter",
      "linter-coffeelint",
      "vim-mode"
    ],
    "themes": [
      "atom-dark-ui",
      "solarized-dark-syntax"
    ],
    "autoHideMenuBar": true
  },
  "motepair": {
    "userEmail": "lui..@g...com"
  }
}
```
### Installed Packages

``` coffee
# User
minimap, v4.1.3
motepair, v0.18.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by ronniebarker** [comment]
Every time we open a file, a stack of tabs with empty copies open with the title "filename - undefined\undefined"

**Comment by luizbafilho** [comment]
@ronniebarker Your bug is probably different than this one. What happens is Atom identifies being the same because it generates the same type of error but in a different part of the code. I'm going to close this one, and as soon as you get the bug, use the atom to report it. Then I'll be able to see exactly what is your problem.

If you want, you can ping me at: https://gitter.im/motepair/motepair
