### ISSUE TITLE
Invalid Url

### ISSUE THREAD

**Issue by awitherow** [motepair/motepair#45]
This happens when I attempt to connect.

We have a server and it is running with the port 8080.

/Users/401174/.atom/packages/motepair/node_modules/ws/lib/WebSocket.js:574

```
Error: invalid url
    at WebSocket.initAsClient (/Users/401174/.atom/packages/motepair/node_modules/ws/lib/WebSocket.js:574:47)
    at new WebSocket (/Users/401174/.atom/packages/motepair/node_modules/ws/lib/WebSocket.js:78:18)
    at Object.module.exports.createSocketConnection (/Users/401174/.atom/packages/motepair/lib/main.coffee:48:9)
    at Object.module.exports.connect (/Users/401174/.atom/packages/motepair/lib/main.coffee:80:13)
    at space-pen-div.<anonymous> (/Users/401174/.atom/packages/motepair/lib/main.coffee:62:12)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

**Comment by luizbafilho** [comment]
Hi @awitherow could you paste your config file here so I can see how did you set the url.

![image](https://cloud.githubusercontent.com/assets/355751/18068502/fa428eda-6e17-11e6-86cf-29259bb76d61.png)
