### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by felipero** [motepair/motepair#5]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.177.0
**System**: Mac OS X 10.10.2
**Thrown From**: [motepair](https://github.com/motepair/motepair) package, v0.11.0
### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/felipero/.atom/packages/motepair/lib/remote-cursor-view.coffee:7

TypeError: undefined is not a function
  at RemoteCursorView.initialize (/Users/felipero/.atom/packages/motepair/lib/remote-cursor-view.coffee:7:23)
  at RemoteCursorView.View (/Users/felipero/.atom/packages/motepair/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at new RemoteCursorView (/Users/felipero/.atom/packages/motepair/lib/remote-cursor-view.coffee:6:3)
  at EventHandler.oncursor (/Users/felipero/.atom/packages/motepair/lib/event_handler.coffee:45:31)
  at WebSocket.<anonymous> (/Users/felipero/.atom/packages/motepair/lib/event_handler.coffee:65:9)
  at WebSocket.emit (events.js:138:20)
  at Receiver.ontext (/Users/felipero/.atom/packages/motepair/node_modules/ws/lib/WebSocket.js:798:10)
  at /Users/felipero/.atom/packages/motepair/node_modules/ws/lib/Receiver.js:473:18
  at /Users/felipero/.atom/packages/motepair/node_modules/ws/lib/Receiver.js:357:7
  at /Users/felipero/.atom/packages/motepair/node_modules/ws/lib/PerMessageDeflate.js:217:5
  at afterWrite (_stream_writable.js:363:3)
  at onwrite (_stream_writable.js:354:7)
  at WritableState.onwrite (_stream_writable.js:107:5)
  at afterTransform (_stream_transform.js:101:5)
  at TransformState.afterTransform (_stream_transform.js:76:12)
  at Zlib.callback (zlib.js:612:5)

```
### Commands

```
     -7:45.4 motepair:connect (atom-text-editor.editor)
     -7:42.8 core:select-all (atom-text-editor.editor.mini)
     -7:42.0 core:copy (atom-text-editor.editor.mini)
     -0:39.6 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
     -0:17.3 core:save (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "ignoredNames": [
      ".git .DS_Store .idea"
    ],
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "projectHome": "/Users/felipero/workspace"
  }
}
```
### Installed Packages

``` coffee
# User
haskell-ghc-mod, v0.4.1
ide-haskell, v0.3.1
language-fish-shell, v1.0.1
motepair, v0.11.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by leonmaia** [comment]
:+1: fixed :fireworks:
