### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replace' of null

### ISSUE THREAD

**Issue by mvoto** [motepair/motepair#52]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 16.04.2
**Thrown From**: [motepair](https://github.com/motepair/motepair) package 0.24.0

### Stack Trace

Uncaught TypeError: Cannot read property 'replace' of null

```
At /home/mvoto/.atom/packages/motepair/lib/event_handler.coffee:89

TypeError: Cannot read property 'replace' of null
    at EventHandler.locateProjectPath (/packages/motepair/lib/event_handler.coffee:89:39)
    at EventHandler.locateFilePath (/packages/motepair/lib/event_handler.coffee:102:22)
    at EventHandler.onselect (/packages/motepair/lib/event_handler.coffee:53:52)
    at /packages/motepair/lib/event_handler.coffee:133:11)
    at emitTwo (events.js:111:20)
    at WebSocket.emit (events.js:191:7)
    at Receiver.ontext (/packages/motepair/node_modules/ws/lib/WebSocket.js:816:10)
    at /packages/motepair/node_modules/ws/lib/Receiver.js:477:18
    at /packages/motepair/node_modules/ws/lib/Receiver.js:361:7
    at /packages/motepair/node_modules/ws/lib/PerMessageDeflate.js:238:5
    at afterWrite (_stream_writable.js:361:3)
    at onwrite (_stream_writable.js:352:7)
    at WritableState.onwrite (_stream_writable.js:89:5)
    at afterTransform (_stream_transform.js:79:3)
    at TransformState.afterTransform (_stream_transform.js:54:12)
    at Zlib.callback (zlib.js:639:5)
```

### Commands

```
     -2:34.4.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:31.7.0 core:confirm (input.hidden-input)
     -2:31.6.0 motepair:connect (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:22 core:confirm (input.hidden-input)
     -0:32.1.0 fuzzy-finder:toggle-file-finder (atom-pane.pane)
     -0:31.1.0 editor:consolidate-selections (input.hidden-input)
     -0:31.1.0 core:cancel (input.hidden-input)
     -0:30.6.0 application:new-file (atom-pane.pane)
     -0:26.4.0 editor:newline (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.4.3 
intentions 1.1.2 
language-elixir 0.19.0 
linter 2.2.0 
linter-markdown 4.0.1 
linter-rubocop 2.1.1 
linter-ui-default 1.6.2 
motepair 0.24.0 
rails-partials 0.9.2 
vim-mode-plus 0.93.0 
```

**Comment by gobert** [comment]
Kind of the same

# Uncaught TypeError: Cannot create property 'type' on string 'control frames cannot have the Per-m...

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.0 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [motepair](https://github.com/motepair/motepair) package 0.24.0


### Stack Trace

Uncaught TypeError: Cannot create property 'type' on string 'control frames cannot have the Per-message Compressed bits'

```
At /Users/geoffroy.gobert/.atom/packages/motepair/node_modules/ws/lib/WebSocket.js:426

TypeError: Cannot create property 'type' on string 'control frames cannot have the Per-message Compressed bits'
    at WebSocket.onError (/packages/motepair/node_modules/ws/lib/WebSocket.js:426:16)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at Receiver.onerror (/packages/motepair/node_modules/ws/lib/WebSocket.js:851:10)
    at Receiver.error (/packages/motepair/node_modules/ws/lib/Receiver.js:321:8)
    at Receiver.processPacket (/packages/motepair/node_modules/ws/lib/Receiver.js:222:12)
    at Receiver.add (/packages/motepair/node_modules/ws/lib/Receiver.js:95:24)
    at Socket.realHandler (/packages/motepair/node_modules/ws/lib/WebSocket.js:800:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
```

### Commands

```
  2x -8:41.5.0 core:undo (input.hidden-input)
     -6:54.3.0 editor:consolidate-selections (input.hidden-input)
     -6:54.3.0 core:cancel (input.hidden-input)
     -0:09.3.0 command-palette:toggle (input.hidden-input)
     -0:07.5.0 core:confirm (input.hidden-input)
     -0:07.5.0 motepair:connect (input.hidden-input)
     -0:06.9.0 core:select-all (input.hidden-input)
     -0:06.8.0 core:copy (input.hidden-input)
     -0:06.2.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.4.3 
intentions 1.1.5 
linter 2.2.0 
linter-rubocop 2.2.0 
linter-ui-default 1.6.10 
motepair 0.24.0 
```
